### ISSUE TITLE
为什么不支持async的render的写法

### ISSUE THREAD

**Issue by liuyu322** [hubcarl/egg-view-vue-ssr#2]
![image](https://user-images.githubusercontent.com/5425933/27473508-11637c8c-5832-11e7-81d0-97660f721930.png)

**Comment by hubcarl** [comment]
es7 特性暂时还没有试过，还需要后面验证一下

**Comment by jacksky007** [comment]
https://github.com/hubcarl/egg-vue-webpack-boilerplate/issues/15 那个404应该跟这个问题是同样的原因。我觉得问题在于直接覆盖 ```context.render``` 而不是用 view 插件机制来注册一个新的 view engine 的话是会有很多问题的。

1. 目前 https://github.com/hubcarl/egg-view-vue-ssr/blob/master/app/extend/context.js#L12 用 generator function 覆盖方式实现的话，那么 controller 就只能用 generator function。
2. 另外更严重的影响在于，没办法做多种模板引擎共存，egg 本身提供的 view 插件机制被彻底抛弃了，不知道对这个问题是否有过考虑。我觉得可以修改下目前的实现，采用跟 https://github.com/hubcarl/egg-view-vue 等其他 egg view 插件一样的机制来注册一个真的 view engine。

**Comment by jacksky007** [comment]
我尝试了使用 egg view 插件的机制来实现，遇到些棘手的麻烦

1. .js 后缀被 egg-view-vue 先注册使用后，egg-view-vue-ssr 无法覆盖，这应该是 egg 的 viewManager 内部实现决定的，虽然我可以采用些方法在运行 egg 之前修改 egg-view-vue 里的 config 文件，但是这方法太 tricky 太不 robust 了
2. egg-view 会把诸如 ```ctx, request, helper``` 等一般服务端模板引擎需要的内容合并到 ```locals```，而 vuessr
 不需要这些数据，但是``` {state: locals}``` 会把这些全都放到 ```window.__INITIAL_STATE__``` 中

所以我在自己的 fork 中曲线救国了，给 context.js 里的 render 换个名字 vueRender，是个普通函数，返回Promise，那么就可以支持 generator function 和 async function。

至于本 repo 如何改进，要看 @hubcarl 后面怎么思考了，如果愿意的话可以一起探讨。

**Comment by hubcarl** [comment]
好的，我这边根据你们反馈看看怎么改进

**Comment by hubcarl** [comment]
@liuyu322 @jacksky007  egg-view-vue-ssr 我改为返回promise了(2.1.1最新版本)，现在测试已经支持async和await了,

**Comment by jacksky007** [comment]
@hubcarl 多模板引擎共存还是无法工作，是否有考虑过处理这个问题。

**Comment by hubcarl** [comment]
多引擎这里就不能采用覆盖的方式，只能创建注册一个新的view engine， 不知道是否有这种紧迫的需要，如果需要后面Node8正式发布，考虑支持

**Comment by hubcarl** [comment]
@jacksky007  多引擎可以这样实现， 单独写一个 ssr插件， 然后 依赖egg－view-vue
插件（但不启用），仅仅作为依赖，使用它的engine实现render即可
