### ISSUE TITLE
normalizeLocals 建议

### ISSUE THREAD

**Issue by meidea** [hubcarl/egg-view-vue-ssr#6]
https://github.com/hubcarl/egg-view-vue-ssr/blob/ad3654e5120904b35ebbaa094e215b75cadcd286/lib/engine.js#L46

建议增加一个配置，用来控制normalizeLocals是否将ctx.app.locals与locals合并

**Comment by hubcarl** [comment]
@meidea  增加了 mergeLocals 配置控制是否合并 locals，默认true
